services:
  technodevlabs:
    image: postgres
    restart: always
    container_name: technodevlabs
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: technodevlabs
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
