services:
  technodevlabs:
    image: postgres
    restart: always
    container_name: technodevlabs
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: technodevlabs
      POSTGRES_DB: technodevlabs
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
